import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import RouteGuard from "../components/routeGuard";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-indigo-50 via-pink-50 to-amber-50 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900`}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem >
        <RouteGuard>{children}</RouteGuard>
      </ThemeProvider>
      
      </body>
    </html>
  );
}
